name: Desafio Docker Pull

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to deploy on docker'
        required: true
        default: 'select'
        type: string

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do Docker
        run: docker -v

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Instala imagem inputada
        run: docker pull ${{ inputs.image }}

      - name: Lista imagens
        run: docker images

      - name: Roda scout na imagem baixada
        uses: docker/scout-action@v1
        with:
          image: local://${{ inputs.image }}
          command: quickview
          # only-severities: critical,high
          # exit-code: true
          # # Optional: Add results as a comment in a PR
          # write-comment: true