name: Funcionamento entre steps # Nome principal do workflow.

on:                   # Como esse workflow será triggado.
  workflow_dispatch   # Nesse caso, apenas manualmente.

jobs:                             # Inicio das especificações dos jobs.
  entre-steps:                       # Nome do job.
    runs-on: ubuntu-latest        # Qual máquina vai rodar.
    steps:                        # Inicio das especificações dos passos que o job vai seguir.
      - name: Confere versão do Ubuntu    # Nome do passo.
        run: cat /etc/os-release          # Execução do passo.
      
      - name: Cria um arquivo                                                               # Nome do passo.
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips!" > mensagem.txt    # Execução do passo.

      - name: Lê o arquivo criado anteriormente                                             # Nome do passo.
        run: cat mensagem.txt                                                               # Execução do passo.